import { useState } from "react";
import Image from "next/image";
import { Configuration, OpenAIApi } from "openai";
import { MetaHeader } from "~~/components/MetaHeader";

interface State {
  imageUrl: string;
  size: string;
  generatedText: string;
  isLoading: boolean;
}

interface TextResponse {
  choices: Choice[];
}

interface Choice {
  text: string;
}

interface ImageResponse {
  data: ImageData[];
}

interface ImageData {
  url: string;
}

function Remember() {
  const [state, setState] = useState<State>({
    imageUrl: "/loading.gif",
    size: "medium",
    generatedText: "",
    isLoading: false,
  });

  const getImageAndText = async () => {
    setState({ ...state, imageUrl: "/loading.gif", generatedText: "", isLoading: true });

    const configuration = new Configuration({
      apiKey: "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",
    });

    const openai = new OpenAIApi(configuration);

    const size = state.size;

    openai
      .createCompletion({
        model: "text-davinci-003",
        prompt: `Create a prompt as a teaching poem in Pali using at least one of the three marks of existence as a guide; then use Pali and translate to English. Write the full English text first, then the Pali. Max 50 words`,
        temperature: 0.2,
        max_tokens: 300,
        top_p: 1,
        frequency_penalty: 0,
        presence_penalty: 0,
      })
      .then(response => {
        const responseData = response.data as TextResponse;
        setState({
          ...state,
          imageUrl: "/loading.gif",
          generatedText: `${responseData.choices[0].text}`,
        });

        openai
          .createImage({
            prompt: `black and white, minimalist, pure light, abstract life`,
            n: 1,
            size: size === "large" ? "1024x1024" : size === "medium" ? "512x512" : "256x256",
          })
          .then(response => {
            const responseData = response.data as ImageResponse;
            setState({
              ...state,
              imageUrl: `${responseData.data[0].url}`,
              isLoading: false,
            });
          })
          .catch((error: any) => {
            console.log(error);
          });
      });
  };

  return (
    <>
      <MetaHeader />
      <div className="flex items-center flex-col flex-grow pt-10">
        <div className="px-5 md:w-1/2">
          <h1 className="my-6">
            <span className="block text-4xl font-bold">Remember This</span>
          </h1>
          <p>
            Named after the Buddhist term for &lsquo;mindfulness&rsquo; or &lsquo;remembering&rsquo;, Sati combines
            advanced text and image generation technologies to help humans recall and reflect upon the Three Marks of
            Existence in Buddhist philosophy.
          </p>
          <ul className="px-8 font-bold list-disc">
            <li>Anicca (Impermanence)</li>
            <li>Dukkha (Suffering)</li>
            <li>Anatta (Non-self)</li>
          </ul>
          <p>
            This page creates vivid AI-generated visuals, paired with enlightening narratives, to symbolize these three
            profound truths. Importantly, both the image and text presented by Sati are <b>ephemeral</b>, mirroring the
            teaching of <i>Anicca</i> and emphasizing the impermanent nature of all phenomena. We hope this will enhance
            your mindful engagement, making the exploration of ancient Buddhist wisdom a dynamic, aesthetic experience
            in the AI age.
          </p>
        </div>
        <div className="text-center">
          <button
            className={`btn btn-primary px-10 rounded-full space-x-3 ${
              state.isLoading ? "loading before:!w-4 before:!h-4 before:!mx-0" : ""
            }`}
            onClick={getImageAndText}
          >
            {state.isLoading ? "" : "Generate Temporarily"}
          </button>
        </div>
        <div className="px-5 md:w-1/2 border rounded my-8">
          <p className="my-6 mx-auto w-3/4 font-bold text-center">{state.generatedText}</p>
          <div className="w-full mx-auto flex justify-center mb-8">
            <Image width={512} height={512} alt="Generated by Sati" src={state.imageUrl} />
          </div>
        </div>
      </div>
    </>
  );
}

export default Remember;
