import { useState } from "react";
import getConfig from "next/config";
import Image from "next/image";
import Link from "next/link";
import { Configuration, OpenAIApi } from "openai";
import { MetaHeader } from "~~/components/MetaHeader";

const { publicRuntimeConfig } = getConfig();

interface State {
  imageUrl: string;
  size: string;
  generatedText: string;
  isLoading: boolean;
}

interface TextResponse {
  choices: Choice[];
}

interface Choice {
  text: string;
}

interface ImageResponse {
  data: ImageData[];
}

interface ImageData {
  url: string;
}

function Remember() {
  const [state, setState] = useState<State>({
    imageUrl: "/loading.gif",
    size: "medium",
    generatedText: "",
    isLoading: false,
  });

  const apiKey = publicRuntimeConfig.OPENAI_API_KEY;

  const getImageAndText = async () => {
    setState({ ...state, imageUrl: "/loading.gif", generatedText: "", isLoading: true });

    const configuration = new Configuration({
      apiKey: apiKey,
    });

    const openai = new OpenAIApi(configuration);

    const size = state.size;

    openai
      .createCompletion({
        model: "text-davinci-003",
        prompt: `Create a prompt as a teaching poem in Pali using at least one of the three marks of existence as a guide; then use Pali and translate to English. Write the full English text first, then the Pali. Max 50 words.`,
        temperature: 0.2,
        max_tokens: 300,
        top_p: 1,
        frequency_penalty: 0,
        presence_penalty: 0,
      })
      .then(response => {
        const responseData = response.data as TextResponse;
        setState({
          ...state,
          imageUrl: "/loading.gif",
          generatedText: `${responseData.choices[0].text}`,
        });

        openai
          .createImage({
            prompt: `black and white, minimalist, pure light, abstract life`,
            n: 1,
            size: size === "large" ? "1024x1024" : size === "medium" ? "512x512" : "256x256",
          })
          .then(response => {
            const responseData = response.data as ImageResponse;
            setState({
              ...state,
              imageUrl: `${responseData.data[0].url}`,
              isLoading: false,
            });
          })
          .catch((error: any) => {
            console.log(error);
          });
      });
  };

  return (
    <>
      <MetaHeader />
      <div className="flex items-center flex-col flex-grow pt-10">
        <div className="px-5 md:w-1/2">
          <h1 className="my-6">
            <span className="block text-4xl font-bold">Remember This</span>
          </h1>
          <p>
            Named after the Buddhist term for &lsquo;mindfulness&rsquo; or &lsquo;remembering&rsquo;, Sati combines
            advanced text and image generation technologies to help humans recall and reflect upon the Three Marks of
            Existence in Buddhist philosophy.
          </p>
          <ul className="px-8 font-bold list-disc">
            <li>Anicca (Impermanence)</li>
            <li>Dukkha (Suffering)</li>
            <li>Anatta (Non-self)</li>
          </ul>
          <p>
            This page creates vivid AI-generated visuals, paired with enlightening narratives, to symbolize these three
            profound truths. Importantly, both the image and text presented by Sati are <b>ephemeral</b>, mirroring the
            teaching of <i>Anicca</i> and emphasizing the impermanent nature of all phenomena. We hope this will enhance
            your mindful engagement, making the exploration of ancient Buddhist wisdom a dynamic, aesthetic experience
            in the AI age.
          </p>
        </div>
        <div className="text-center">
          <button
            className={`btn btn-primary px-10 rounded-full space-x-3 ${
              state.isLoading ? "loading before:!w-4 before:!h-4 before:!mx-0" : ""
            }`}
            onClick={getImageAndText}
          >
            {state.isLoading ? "" : "Generate Temporarily"}
          </button>
        </div>
        <div className="px-5 md:w-1/2 border rounded my-8">
          <p className="my-6 mx-auto w-3/4 font-bold text-center">{state.generatedText}</p>
          <div className="w-full mx-auto flex justify-center mb-8">
            <Image width={512} height={512} alt="Generated by Sati" src={state.imageUrl} />
          </div>
        </div>

        <div className="px-5 md:w-1/2">
          <h1 className="my-6">
            <span className="block text-4xl font-bold">Contemplative Digital Art</span>
          </h1>
          <p>
            In the realm of contemplative digital arts, I have found a dance of awareness weaving together themes of the
            body, impermanence, nature, observation, and emptiness. These works, like reflections in a mirror, enhance
            my understanding of the world directly in front of me.
          </p>
          <p>
            Bound together by algorithmic design and inherent transience, these creations reflect the Buddhist teaching
            of impermanence. Time here is an integral part of the creative process.
          </p>
          <p>
            While not all works utilize AI, they are all anchored in the digital realm. My creative practice navigates
            through generative design, creative coding, generative AI, and interactive web design. Adapting to the
            subject matter at hand, these tools sometimes serve as didactic instruments, other times adopting an
            unabashedly queer aesthetic.
          </p>
          <p>
            And now, these creations are my gift and offering to you. Like a handful of leaves offered in the forest,
            they are intended to inspire, provoke, and awaken. May they serve as a catalyst for your own journey of
            discovery. May they invite you into a dance with the ephemeral and the eternal, the tangible and the
            abstract, the personal and the universal. May they echo in your mind, resonate in your heart, and find a
            home in your consciousness. This is my offering to you, a token of generosity and a manifestation of
            interconnectedness in this vast digital realm:
          </p>
        </div>
        <div className="flex flex-wrap gap-2 md:w-1/2 mb-2">
          <div className="btn btn-primary px-4 mb-2">
            <Link href="/sketch">Body of the Breath</Link>
          </div>
          <div className="btn btn-primary px-4 mb-2">
            <Link href="https://marlonbarrios.github.io/black_ink_enso/">Dymanic Enso</Link>
          </div>
          <div className="btn btn-primary px-4 mb-2">
            <Link href="https://marlonbarrios.github.io/chromatic_crescent/">Chromatic Crescent</Link>
          </div>
          <div className="btn btn-primary px-4 mb-2">
            <Link href="https://marlonbarrios.github.io/spirograh100squares/">Emergent Mandalas</Link>
          </div>
          <div className="btn btn-primary px-4 mb-2">
            <Link href="https://medium.com/@marlon_21867/canonical-soft-space-01-a751d337da2a">Canonical</Link>
          </div>
          <div className="btn btn-primary px-4 mb-2">
            <Link href="https://medium.com/@marlon_21867/thick-present-awareness-guided-meditation-a-post-humanist-practice-b0ed88521f01">
              Thick Present Awareness
            </Link>
          </div>
          <div className="btn btn-primary px-4 mb-2">
            <Link href="https://marlonbarrios.github.io/flow_field_02/">Emergent Paths</Link>
          </div>
        </div>
      </div>
    </>
  );
}

export default Remember;
